#!/bin/sh
# Copyright (C) 2008-2010 Ali Gangji
# Distributed under the terms of the GNU General Public License v3
# This file is part of StarbugPHP
#/// @file console Starbug console. Run ./console to enter the console
#/// @author Ali Gangji <ali@neonrain.com>
#/// @ingroup script
php -d auto_prepend_file=script/console.php -a
