version: "3.7"
services:
  apache:
    image: agangji/apache
    networks:
      default:
        aliases:
          - sb.local.com
    volumes:
      - .:/var/www/html
      - ~/.docker/certs/server.key:/etc/pki/tls/private/localhost.key
      - ~/.docker/certs/server.crt:/etc/pki/tls/certs/localhost.crt
  php:
    image: agangji/php:7.4
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .:/var/www/html
      - mariadb-data:/var/lib/mysql
    environment:
      - PHP_USER=$PHP_USER
      - PHP_GROUP=$PHP_GROUP
      - PHP_UID=$PHP_UID
      - PHP_GID=$PHP_GID
    command: ["precreate-user.sh", "php-fpm", "-F"]
  mariadb:
    image: agangji/mariadb:10.2
    volumes:
      - mariadb-data:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
  default-queue:
    image: agangji/php:7.3
    restart: always
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .:/var/www/html
      - mariadb-data:/var/lib/mysql
    environment:
      - PHP_USER=$PHP_USER
      - PHP_GROUP=$PHP_GROUP
      - PHP_UID=$PHP_UID
      - PHP_GID=$PHP_GID
    command: ["precreate-user.sh", "php", "sb", "process-queue"]

volumes:
  mariadb-data:
