#!/usr/bin/php -Cq
<?php
	namespace Starbug\Core;
	define('SB_CLI', true);
	$status = 0;
	if (file_exists("etc/Host.php")) {
		include("core/cli.php");
		$status = 1;
	}
	$command = array_shift($argv);
	$script = array_shift($argv);
	$path = $namespace = false;
	if ($status) {
			$locations = $locator->locate($script.".php", "script");
			$path = end($locations);
			$namespace = key($locations);
	} else $path = "core/app/script/$script.php";
	if (file_exists($path)) include($path);
	$classname = str_replace(' ', '', ucwords(str_replace('-', ' ', $script)))."Command";
	if (class_exists($namespace."\\".$classname)) {
		$command = $container->get($namespace."\\".$classname);
		$command->run($argv);
	}
?>
