#!/usr/bin/php -Cq
<?php
  namespace Starbug\Core;
  chdir(dirname(__FILE__));
  include("core/cli.php");
  $command = array_shift($argv);
  $script = array_shift($argv);
  $path = $namespace = false;
  $locator = $container->get('Starbug\ResourceLocator\ResourceLocatorInterface');
  $className = $locator->className($script, "Command");
  $command = $container->get($className);
  $command->run($argv);
?>
