version: "3.7"
services:
  chrome:
    image: agangji/chrome
    network_mode: service:php
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/shm:/dev/shm
      - $HOME/.docker/certs/rootCA.pem:/home/chrome/CA.pem
    security_opt:
      - seccomp:app/etc/docker/chrome.json
    command: ["--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--hide-scrollbars"]
