#!/usr/bin/php
<?php
	define('BASE_DIR', str_replace("/script", "", dirname(__FILE__)));
	include(BASE_DIR."/etc/Etc.php");
	include(BASE_DIR."/core/init.php");
	include(BASE_DIR."/core/db/Schemer.php");
	global $schemer;
	$schemer = new Schemer($sb->db);
	include(BASE_DIR."/etc/schema.php");
	$sb->import("util/cli");
	$script = array_shift($argv);
	$what = array_shift($argv);
	if ($what == "sync") $schemer->migrate();
	if ($what == "migrate") {
		$next = array_shift($argv);
		if (false !== strpos($next, ":")) {
			$next = explode(":", $next);
			$from = $next[0];
			$to = $next[1];
			$schemer->migrate($to, $from);
		} else {
			$to = $next;
			$schemer->migrate($to);
		}
	}
	if ($what == "store") {
		$name = array_shift($argv);
		$params = join("  ", $argv);
		$params = starr::star($params);
		$errors = $sb->store($name, $params);
		if (empty($errors)) {
			$id = (empty($params['id'])) ? $sb->insert_id : $params['id'];
			$what = "query";
			$argv = array($name, "where:id='$id'");
		} else {
			foreach($errors as $col => $arr) {
				echo $col.":\n";
				foreach($arr as $e => $m) {
					echo "\t".$m."\n";
				}
			}
		}
	}
	if ($what == "remove") {
		$name = array_shift($argv);
		foreach($argv as $index => $arg) {
			$arg = explode(":", $arg, 2);
			$argv[$index] = $arg[0]."='".$arg[1]."'";
		}
		$params = join(" ", $argv);
		$sb->remove($name, $params);
	}
	if ($what == "query") {
		$name = array_shift($argv);
		$params = join("  ", $argv);
		$records = $sb->query($name, $params);
		echo "query $name $params\n";
		cli::table($records);
	}
?>
