#!/usr/bin/php
<?php
/**
* FILE: script/plugin
* PURPOSE: used to manage plugins
*
* This file is part of StarbugPHP
*
* StarbugPHP - website development kit
* Copyright (C) 2008-2009 Ali Gangji
*
* StarbugPHP is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* StarbugPHP is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with StarbugPHP.  If not, see <http://www.gnu.org/licenses/>.
*/
$help = "Usage: plugin MODE [OPTIONS]\n\n";
$help .= "MODE\tWhat to do\n";
$help .= "    \t\t-i [NAME] - install plugin\n";
$help .= "    \t\t-l - list plugins\n";
$help .= "    \t\t-r [NAME] - remove plugin\n";
if ($argc==2) $argv[2] = "";
include("etc/Etc.php");
include("etc/init.php");
$sb->import("util/plugins");

if ($argv[1] == "-i") { //INSTALL PLUGIN
	if (empty($argv[2])) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	$loc = $argv[2];
	include($loc."/activate.php");
	exit(0);
} else if ($argv[1] == "-l") { //LIST PLUGINS
	$plugins = plugins::available();
	foreach($plugins as $name => $info) fwrite(STDOUT, (($info['active']) ? " a  " : "    ").$name."\n");
	exit(0);
} else if ($argv[1] == "-r") { //UNINSTALL PLUGIN
	if (empty($argv[2])) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	$loc = $argv[2];
	include($loc."/deactivate.php");
	exit(0);
}

?>
