#!/usr/bin/php
<?php
/**
 * This file is part of StarbugPHP
 * @file script/plugin used to manage plugins
 * @author Ali Gangji <ali@neonrain.com>
 * @ingroup script
 */
$help = "Usage: plugin MODE [OPTIONS]\n";
$help .= "MODE\n";
$help .= "  -l                    - list plugins\n";
$help .= "  -a [PLUGIN] [MODEL]   - activate plugin\n";
$help .= "  -d [PLUGIN] [MODEL]   - deactivate plugin\n";
$help .= "  -i [PLUGIN]           - install plugin\n";
$help .= "  -u [PLUGIN]           - uninstall plugin\n\n";
if ($argc==2) $argv[2] = "";
if (!defined('BASE_DIR')) define('BASE_DIR', str_replace("/script", "", dirname(__FILE__)));
if (!defined('STDOUT')) define("STDOUT", fopen("php://stdout", "wb"));
if (!defined('STDIN')) define("STDIN", fopen("php://stdin", "r"));
include(BASE_DIR."/etc/Etc.php");
include(BASE_DIR."/core/init.php");
$sb->import("util/plugins");

if ($argv[1] == "-i") { //INSTALL PLUGIN
	if (empty($argv[2])) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	$loc = $argv[2];
	include($loc."/activate.php");
	exit(0);
} else if ($argv[1] == "-a") { //ACTIVATE PLUGIN
	if ($argc < 4) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	plugins::activate($argv[2], $argv[3]);
} else if ($argv[1] == "-d") { //DEACTIVATE PLUGIN
	if ($argc < 4) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	plugins::deactivate($argv[2], $argv[3]);
} else if ($argv[1] == "-l") { //LIST PLUGINS
	$plugins = plugins::available($argv[2]);
	foreach($plugins as $name => $info) fwrite(STDOUT, (($info['active']) ? " a  " : "    ").$name."\n");
	exit(0);
} else if ($argv[1] == "-u") { //UNINSTALL PLUGIN
	if (empty($argv[2])) {
		fwrite(STDOUT, $help);
		exit(0);
	}
	$loc = $argv[2];
	include($loc."/deactivate.php");
	exit(0);
} else echo $help;

?>
